function y = preprocess(x)
%  Preprocess input x
%    This function expects an input vector x.

% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 11-Jun-2023 20:16:28
%4 4 
%14 simulation
y = wdenoise(x, 13, ...
    'Wavelet', 'db10', ...
    'DenoisingMethod', 'Bayes', ...
    'ThresholdRule', 'Median', ...
    'NoiseEstimate', 'LevelIndependent');
end