function [Peeg_ROI, Feeg_ROI] = spectrum(data)

% Compute power spectrum

% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 03-Jun-2023 14:35:33

% Parameters
frequencyLimits = [0 1]*pi; % Normalized frequency (rad/sample)

% Index into signal time region of interest
timeLimits = [1 1000001]; % samples
data_ROI = data(:)';
data_ROI = data_ROI(timeLimits(1):timeLimits(2));

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[Peeg_ROI, Feeg_ROI] = pspectrum(data_ROI, 'FrequencyLimits',frequencyLimits);
end